name: test
on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  checks: write
  packages: write

jobs:
   deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 