name: test
on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  checks: write
  packages: write

jobs:
   deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: download istio
      run: |
        curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.24.6 TARGET_ARCH=x86_64 sh -
        
    - name: Upload Istio as artifact
      uses: actions/upload-artifact@v3
      with:
        name: istio-files
        path: istio-1.24.6/
